name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create cypress.env.json
        run: |
          printf "%s" "${{ secrets.CYPRESS_ENV_JSON }}" > cypress.env.json
          if ! jq empty cypress.env.json; then
            echo "cypress.env.json is not valid JSON"
            exit 1
          fi
        env:
          CYPRESS_ENV_JSON: ${{ secrets.CYPRESS_ENV_JSON }}

      - name: Check cypress.env.json details
        run: |
          ls -l cypress.env.json
          cat cypress.env.json || echo "cypress.env.json could not be read"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          record: false
          headless: true
          browser: chrome

      - name: Archive Cypress screenshots and videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
